name: Renovate

on:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
    renovate:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/renovatebot/renovate:latest

        steps:
            - name: Run Renovate
              env:
                RENOVATE_AUTO_APPROVE: true
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}

              run: |
                  npm install -g renovate
                  renovate
