name: Renovate

on:
    schedule:
        - cron: '0 0 * * 1'
    workflow_dispatch:

jobs:
    renovate:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/renovatebot/renovate

        steps:
            - name: Run Renovate
              run: |
                  renovate
#                  docker run --rm \
#                    --volume ${{ github.workspace }}/renovate.js:/usr/src/app/config.js \
#                    --env LOG_LEVEL=debug

