name: Renovate

on:
    schedule:
      - cron: '0 0 * * 1-5' #UTC
    workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/renovatebot/renovate
      options: --user root # workaround for checkout

    steps:
      - name: Check out repository
        uses: actions/checkout@v4 # using checkout to access workspace
      - name: Run Renovate
        env:
          # RENOVATE_TOKEN should have access :read_user, api, write_repository (repo checkbox)
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RENOVATE_CONFIG_FILE: ${{ github.workspace }}/renovate_config.js
          RENOVATE_PACKAGE_RULES : """[{
          	matchPackagePatterns: [ '*' ],
          	matchUpdateTypes: [ 'patch' ],
          	groupName: 'all patch dependencies',
          	groupSlug: 'all-patch'
            }]"""
          RENOVATE_EXTENDS : '["config:recommended"]'
          LOG_LEVEL: debug
        run: |
          renovate
