name: Renovate

on:
    schedule:
      - cron: '28 15 * * *'
    workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate
      options: --user root # workaround for checkout
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 # using checkout to access workspace

      - name: Run Renovate
        env:
          RENOVATE_AUTODISCOVER: true # going through all reps
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RENOVATE_CONFIG_FILE: ${{ github.workspace }}/config.js
          RENOVATE_PLATFORM: github
          #RENOVATE_ONBOARDING_CONFIG: true
          RENOVATE_FORK_CREATION: true
          RENOVATE_ONBOARDING_NO_DEPS: true
          LOG_LEVEL: debug
# renovate.json - forkProcessing forked repositories are not onboarded in default, Renovate essentially ignores them

        run: |
          renovate

