name: Renovate

on:
    workflow_dispatch:
jobs:
    renovate:
        name: Renovate
        runs-on: linux
        steps:
            - name: Run Renovate
              run: |
                  docker run --rm \
                    --volume ${{ github.workspace }}/renovate-config.js:/usr/src/app/config.js \
                    --env LOG_LEVEL=debug \
                    mycompany.net/my-registry-remote/renovate/renovate:32.26.3
