name: Renovate

on:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
    renovate:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/renovatebot/renovate:latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run Renovate
              run: |
                  npm install -g renovate
                  renovate --config-file renovate.js
