name: Renovate

on:
    workflow_dispatch:

jobs:
    renovate:
        name: Renovate VM
        runs-on: ubuntu-latest
        container: ubuntu-latest
        timeout-minutes: 15

        services:
            renovate:
                image: ghcr.io/renovatebot/renovate:latest

        steps:
            - name: Run Renovate
              run: |
                  renovate --config-file
#                  docker run --rm \
#                    --volume ${{ github.workspace }}/renovate.js:/usr/src/app/config.js \
#                    --env LOG_LEVEL=debug \
#                    ghcr.io/renovatebot/renovate:latest

