name: Renovate

on:
    schedule:
      - cron: '28 15 * * *'
    workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate
      options: --user root # workaround for checkout
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 # using checkout to access workspace
#      - name: Update size of nodes
#        run: |
#          export NODE_OPTIONS="--max_old_space_size=8192"
      - name: Run Renovate
        env:
          #RENOVATE_AUTODISCOVER: false # going through all reps
          #RENOVATE_ONBOARDING_NO_DEPS: true # should create PR even if it is empty
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_CONFIG_FILE: ${{ github.workspace }}/config.js
          LOG_LEVEL: debug
          #NODE_OPTIONS: "--max_old_space_size=8192"
        run: |
          renovate

