name: Renovate

on:
    schedule:
      - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate
      options: --user root #workaround for checkout
    steps:
      - name: Check out repository
        uses: actions/checkout@v3 #using checkout to access workspace

      - name: Run Renovate
        env:
          RENOVATE_CONFIG_FILE: ${{ github.workspace }}/config.js
          LOG_LEVEL: debug
          github-token: ${{ secrets.GITHUB_TOKEN }}
        run: |
            renovate

#${{ github.workspace }}/config.js:/usr/src/app/config.js
#              env:
#                  LOG_LEVEL: debug
#                  RENOVATE_AUTO_APPROVE: true
#              with:
#                  github-token: ${{ secrets.GITHUB_TOKEN }}
#              run: |
#                  renovate

#                  docker run --rm \


